apiVersion: v1
kind: Service
metadata:
  name: wil-app-service
  labels:
    app: wil-app
spec:
  selector:
    app: wil-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
